### ISSUE TITLE
Forgot to turn off Wait for Debugger

### ISSUE THREAD

**Issue by TheCrafters001** [marwaha-raghav/JackalOS#2]
Hi, it seems like you forgot to turn off the "Wait for Debugger" feature. Is there a way you can turn it off and recompile your first build?

**Comment by AbhinavAtrishi** [comment]
I don't quite understand what you mean by turning off "Wait for Debugger" feature, can you please elaborate a bit more? Are you referring to the waiting for debugger text shown on the VMWare Player before loading the OS?

**Comment by TheCrafters001** [comment]
@AbhinavAtrishi Yes, I am referring to that text, because it blocks the ability to use the OS. I know COSMOS is kinda hard to figure out, but I would like to try your OS :)

**Comment by AbhinavAtrishi** [comment]
Thank you for reporting this issue. I have updated the release and disabled the remote debugger connection.
